namespace: ibm-mq

resources:
- receiver/deployment.yaml
- receiver/service.yaml

- sender/deployment.yaml
- sender/service.yaml
- sender/route.yaml

- mq-ccdt.yaml

# Add .spec.pki.* to the QueueManager for establishing
# mutual TLS between the apps and the Queue Manager
- qm-overlay.yaml

images:
- name: navidsh/mq-sample-receiver
  newTag: 0.0.2-ccdt
- name: navidsh/mq-sample-sender
  newTag: 0.0.2-ccdt
