namespace: ibm-mq

resources:
- receiver/deployment.yaml
- receiver/service.yaml
- receiver/sb.yaml
- receiver/mq-info.yaml

- sender/deployment.yaml
- sender/service.yaml
- sender/route.yaml
- sender/sb.yaml
- sender/mq-info.yaml

- mq-simul.yaml

images:
- name: navidsh/mq-sample-receiver
  newTag: 0.0.2-ccdt
- name: navidsh/mq-sample-sender
  newTag: 0.0.2-ccdt
